### ISSUE TITLE
Plugin doesn't seem to work

### ISSUE THREAD

**Issue by cobrabr** [kbjr/terminus-title-control#5]
I don't see any change to the tab titles, no matter what configuration I set. Currently, I have it set to the default (image below), but nothing happens, neither with already-open tabs nor with newly-opened ones.

![image](https://user-images.githubusercontent.com/724969/59377777-e7dcfc00-8d20-11e9-9da6-05d0c1feecb5.png)

**Comment by kbjr** [comment]
It was broken by an update in the way Terminus creates the `Tab` objects, which don't look the same as they used to. That said, unfortunately I will likely not have the time to get around to looking at it in more depth than that any time soon.
